# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-30 14:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('mobile_no', models.CharField(max_length=15)),
                ('email', models.CharField(blank=True, max_length=30, verbose_name='Email address')),
                ('date_joined', models.DateField(default=django.utils.timezone.now)),
                ('date_left', models.DateField(blank=True, null=True)),
                ('city', models.CharField(max_length=20)),
                ('postcode', models.CharField(max_length=5, verbose_name='Post Code')),
                ('state', models.CharField(max_length=30)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('line1', models.CharField(default='-', max_length=30)),
                ('line2', models.CharField(default='-', max_length=30)),
                ('line3', models.CharField(default='-', max_length=30)),
            ],
            options={
                'ordering': ['first_name'],
                'verbose_name_plural': 'adult',
            },
        ),
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('area', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['name'],
                'verbose_name_plural': 'cell',
            },
        ),
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['name'],
                'verbose_name_plural': 'kelas',
            },
        ),
        migrations.CreateModel(
            name='Kid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='First name')),
                ('last_name', models.CharField(max_length=30, verbose_name='Last name')),
                ('gender', models.CharField(choices=[('B', 'Boy'), ('G', 'Girl')], max_length=1, verbose_name='Gender')),
                ('mobile_no', models.CharField(max_length=15, verbose_name='Mobile no.')),
                ('email', models.CharField(blank=True, max_length=30, verbose_name='Email address')),
                ('date_joined', models.DateField()),
                ('date_left', models.DateField(blank=True, null=True)),
                ('adult_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.Adult')),
                ('cell_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.Cell')),
            ],
            options={
                'ordering': ['first_name'],
                'verbose_name_plural': 'kid',
            },
        ),
        migrations.CreateModel(
            name='Ministry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['name'],
                'verbose_name_plural': 'ministry',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['description'],
                'verbose_name_plural': 'role',
            },
        ),
        migrations.AddField(
            model_name='kid',
            name='role_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.Role'),
        ),
        migrations.AddField(
            model_name='kelas',
            name='ministry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.Ministry'),
        ),
        migrations.AddField(
            model_name='adult',
            name='cell_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.Cell'),
        ),
        migrations.AddField(
            model_name='adult',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.Role'),
        ),
    ]
