# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-30 14:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fpayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Payment_of_period', models.CharField(max_length=4, verbose_name='Payment of period')),
                ('Payment_of_value', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Payment of value')),
            ],
            options={
                'ordering': ['fund_id'],
                'verbose_name_plural': 'fpayment',
            },
        ),
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Promise_of_Faith_No_of_Seats', models.CharField(max_length=3, verbose_name='Promise of Faith No of Seats')),
                ('Promise_of_Faith_Period', models.CharField(max_length=3, verbose_name='Promise of Faith Period')),
                ('Promise_of_Faith_Total', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Promise of Faith Total')),
                ('adult_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.Adult')),
                ('kid_id', smart_selects.db_fields.GroupedForeignKey(blank=True, group_field='adult_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='masters.Kid')),
            ],
            options={
                'ordering': ['adult_id'],
                'verbose_name_plural': 'fund',
            },
        ),
        migrations.AddField(
            model_name='fpayment',
            name='fund_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.Fund'),
        ),
    ]
